import {errorLog} from "../utils/logger.js";
import {errorRes, successRes} from "../utils/response.js";



export const getOrders = async (req, res) => {
    try {

    } catch (err) {
        console.log(errorLog(err.message))
    }
}

export const getOrder = async (req, res) => {
    try {

    } catch (err) {
        console.log(errorLog(err.message))
    }
}

export const createOrder = async (req, res) => {
    try {

    } catch (err) {
        console.log(errorLog(err.message))
    }
}

export const changeOrderStatus = async (req, res) => {
    try {

    } catch (err) {
        console.log(errorLog(err.message))
    }
}